In [ ]:
# Hello! I am a test cell. You can run me to see if your Python environment is working.
# Try pressing 'Ctrl + Enter' and see if you can see the message below.

print("If it is working, it is working. If it is not, it is not.")

# Pandas 02: Join, Combine, and Reshape

In many cases, data can be spread across a number of files or databases. Or, even worse, it can be arranged in a form that is not convenient for analysis. But don't worry! Pandas has very interesting tools that help us combine, join, and rearrange data. So, let's start! But first, let's get introduced to a new data structure (Series()) and a new library (numpy).

### Pandas Series

A Series is a one-dimensional array-like object containing a sequence of values of the **same type** and an associated array of data labels, called its *index*.

The simplest Series is formed from only an array of data:

In [3]:
# Firstly, let's start by importing pandas into our code.
import pandas as pd

# This command configures pandas to format floating-point numbers to display with one decimal place. 
# It affects how numbers are shown in the entire notebook.
pd.options.display.float_format = '{:.1f}'.format

# Now, let's generate a simple Series.
serie1 = pd.Series([4, -3, 7, 2, 1])

print(serie1)

0    4
1   -3
2    7
3    2
4    1
dtype: int64

The output above represents a Series, with the index on the left and the values on the right. Since we did not define an index for the data, by default, the indexes will be integers starting from 0 to N - 1 (where N is the length of the data).

Often, you'll want to create a Series with an index identifying each data point with a label:

In [6]:
serie2 = pd.Series([4, -3, 7, 2, 1], index=['a', 'b', 'c', 'd', 'e'])
print(serie2)

# Question: What happens if the number of indexes is bigger than the number of values? And what about the other way around?

# Question: How can I access one element of `serie2` using its index? And what about accessing 3 elements at the same time?

a    4
b   -3
c    7
d    2
e    1
dtype: int64

In [7]:
# You can create a series from a dictionary by passing the dictionary.
# For instance, let's assume we're working with data on different planets
# in our solar system, such as their average distance from the sun (in million kilometers).

distances = {
    'Mercury': 57.9,
    'Venus': 108.2,
    'Earth': 149.6,
    'Mars': 227.9,
    'Jupiter': 778.5
}
s_distances = pd.Series(distances)
print(s_distances)

Mercury    57.9
Venus     108.2
Earth     149.6
Mars      227.9
Jupiter   778.5
dtype: float64

### Numpy

The Numerical Python (NumPy) library provides the data structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python (focus here on the word NUMERICAL). NumPy contains, among other things:

- A multidimensional array object (ndarray)
- Functions for performing element-wise computations (with arrays or mathematical operations between arrays)
- Tools for reading and writing array-based datasets to disk
- Linear algebra operations, Fourier transform, and random number generation

Moreover, NumPy serves as a container for data to be passed between algorithms and libraries. In this course, we will not focus on NumPy, but we will see some of NumPy's functions (especially the ones to generate random numbers).

To install NumPy, go to the Miniconda terminal, activate the code environment (if you are using one), and use pip:

```bash
pip install numpy
```

In [11]:
import numpy as np

# A very common use of NumPy is to generate random data. Let's see an example,
# where we generate a list with five random numbers.

random_numbers = np.random.uniform(size=5)
print(random_numbers)

# TODO: Generate an array with 10 uniform random elements with values between 0 and 5.
np.random.uniform(low=0, high=5, size=10)
# TODO: Use another distribution, let's say the exponential one, to generate 10 random numbers.
np.random.exponential(scale=1, size=10)

[0.38305476 0.96744954 0.36922268 0.03911828 0.63717674]

array([0.05073122, 0.41363237, 2.39376279, 0.50291313, 0.37185527,
       0.05307627, 0.01014054, 0.05079184, 0.038271  , 0.5176614 ])

## Pandas: Hierarchical Indexing

Back to Pandas. **Hierarchical indexing** is an important feature of Pandas that enables you to have multiple (two or more) index levels on an axis. What does that mean? Essentially, it provides a way for you to work with higher-dimensional data in a lower-dimensional form. Let's see an example. Create a Series with a list of lists (or arrays) as the index:

In [12]:
uni_distribution = np.random.uniform(size=9)

data = pd.Series(uni_distribution, index=[["a", "a", "b", "b", "c", "c", "c", "d", "d"], 
                                          [1, 2, 3, 1, 3, 1, 2, 2, 3]]) 
print(data)

# What you're seeing is the view of a Series with MultiIndex as its index.
data['a']

a  1   0.2
   2   0.2
b  3   0.9
   1   0.4
c  3   0.0
   1   0.0
   2   0.4
d  2   0.5
   3   0.6
dtype: float64

1   0.2
2   0.2
dtype: float64

In [14]:
# With a hierarchically indexed object, it is possible to concisely select subsets of the data.
# How can we do that?
# TODO: Select the index 'a' of the data.
a = data['a']
print(a)
# We can also select indexes using the slicing notation with the operator ':'.
BtoD = data['b':'d']
print(BtoD)

1   0.2
2   0.2
dtype: float64
b  3   0.9
   1   0.4
c  3   0.0
   1   0.0
   2   0.4
d  2   0.5
   3   0.6
dtype: float64

The MultiIndex also allows us to perform an "inner" level selection using the .loc function (see below).

Let's break it down (because it is important):

**[:, 2]**: Inside the .loc[] method, the comma separates row selectors from column selectors.

Here, you're not specifying any row selector (before the comma), which implies you want to select all rows. The 2 after the comma specifies that you are interested in the second level of the index. Since `data` is a Series with a multiindex, then data.loc[:, 2] selects all data points where the second level of the index has the value 2. Since it's a Series, there are no columns to select, so the second part of the loc selection is actually referring to the second level of the multiindex.

In [ ]:
data.loc[:, 2]

Hierarchical indexing plays an important role in reshaping data and in **group-based operations** (in fact, that is the only reason we are seeing it right now. GROUP-BASED OPERATIONS!). With hierarchical indexing, you can rearrange this data into a DataFrame using its unstack method:

In [ ]:
df = data.unstack()
# TODO: Print df. What is the type of df?

# The inverse operation of unstack is stack.
# df.stack()

# Dataframe Joins

Merge or join operations combine datasets by linking rows using one or more keys. These algorithms are very common and important in relational databases. In Pandas, the `.merge` function is the main entry point for using these types of algorithms with the data stored in DataFrames.

Let's see an example:

In [16]:
# First, let's create two dataframes.

df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7))})

df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3))})

# Now let's apply the merge function.
df3 = pd.merge(df1, df2, on="key")

# Can you explain the merge table below?
# Tip: Print df1 and df2 to help with your explanation.

display(df1)
display(df2)
display(df3)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

  key  data2
0   a      0
1   b      1
2   d      2

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

By default, `pandas.merge` performs an "inner" join; the keys in the result are the **intersection** of both tables.

Therefore, the `pd.merge(df1, df2, on="key")` instructs Pandas to perform a SQL-like join operation on `df1` and `df2` using the "key" column as the basis for the merge. The default merge operation is an inner join, which means the result will include only those rows that have matching values in the "key" column in both `df1` and `df2`.

In [ ]:
# If the column names to join on are different in each dataframe, you can specify them separately.

df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7))})

df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3))})

pd.merge(df3, df4, left_on="lkey", right_on="rkey")

# Question: Where are the "c" and "d" data?

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

Other possible options are "left", "right", and "outer". The outer join takes the union of the keys, combining the effect of applying both left and right joins.

Option       | Behaviour
-------------|-----------------------------------------------
how="inner"  | Use only the key combinations observed in both tables
how="left"   | Use all key combinations found in the left table
how="right"  | Use all key combinations found in the right table
how="outer"  | Use all key combinations observed in both tables together

In [ ]:
pd.merge(df1, df2, how="outer")

In [ ]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

# Activity

Imagine we have two datasets: one containing order details from an e-commerce platform and the other containing product details. We want to merge these datasets to get a complete view of each order, including product information.

Use the code below to create the datasets:

In [21]:
# Create an orders dataset
df_orders = pd.DataFrame({
    'OrderID': [1, 2, 3, 4, 5],  
    'ProductID': ['A', 'B', 'A', 'C', 'D'],  
    'Quantity': [2, 1, 3, 2, 4]  
})

# Creating the second DataFrame with product details
df_products = pd.DataFrame({
    'ProductID': ['A', 'B', 'C', 'D', 'E'],
    'ProductName': ['Widget', 'Gadget', 'Thingamajig', 'Doodad', 'Windows'],
    'Price': [25.00, 15.00, 10.00, 7.50, 0.50]
})

Use the merge operation to answer the following questions:

1. What is the total value of each order? Calculate this by multiplying the quantity of each product by its price.

2. Are there any products listed in `df_products` that have never been ordered?

In [ ]:
# Question 1
pd.merge(df_orders, df_products, on='ProductID', how='inner')

   OrderID ProductID  Quantity  ProductName  Price
0        1         A         2       Widget   25.0
1        2         B         1       Gadget   15.0
2        3         A         3       Widget   25.0
3        4         C         2  Thingamajig   10.0
4        5         D         4       Doodad    7.5

In [24]:
# Question 2
pd.merge(df_orders, df_products, on='ProductID', how='right')

   OrderID ProductID  Quantity  ProductName  Price
0      1.0         A       2.0       Widget   25.0
1      3.0         A       3.0       Widget   25.0
2      2.0         B       1.0       Gadget   15.0
3      4.0         C       2.0  Thingamajig   10.0
4      5.0         D       4.0       Doodad    7.5
5      NaN         E       NaN      Windows    0.5

# Join Function

DataFrame has a join instance method for merging by index. It is used to combine many DataFrame objects having the same or similar index but non-overlapping columns.

Imagine we have two sets of data: one containing user information and the other containing user preferences. Each DataFrame uses the user ID as the index. We want to join these two DataFrames to create a unified view of the user data.

In [ ]:
df_users = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                         'Age': [25, 30, 35, 40]
                        }, index=['User1', 'User2', 'User3', 'User4'])
df_preferences = pd.DataFrame({'Favorite Color': ['Blue', 'Green', 'Red', 'Yellow'],
                               'Favorite Food': ['Pizza', 'Sushi', 'Burger', 'Salad']
                               }, index=['User1', 'User2', 'User3', 'User4'])

In [ ]:
# Now, we want to combine these DataFrames to see each user's information alongside their preferences. 
# Since both DataFrames use user IDs as their indexes, we can easily join them using the .join() method.
df_combined = df_users.join(df_preferences)

# What would happen if you didn't have the preferences of a user, let's say 'User4'?

# Concatenating Along an Axis

Another very common and useful operation in Pandas is the data combination operation called concatenation or stacking.

Suppose you have sales data for the first and second quarters of the year, stored in two separate DataFrames. Each DataFrame contains the same columns: Salesperson, Product, and SalesAmount. You want to concatenate these DataFrames to analyze the sales data for the first half of the year.

In [ ]:
# Sales data for Q1
df_q1_sales = pd.DataFrame({
    'Salesperson': ['Alice', 'Bob', 'Charlie'],
    'Product': ['Laptop', 'Tablet', 'Monitor'],
    'SalesAmount': [1200, 850, 600]
})

# Sales data for Q2
df_q2_sales = pd.DataFrame({
    'Salesperson': ['Alice', 'Bob', 'Dave'],
    'Product': ['Monitor', 'Laptop', 'Tablet'],
    'SalesAmount': [700, 1200, 950]
})

In [ ]:
# We want to concatenate these DataFrames vertically to create a single DataFrame with sales data for both quarters.
df_combined_sales = pd.concat([df_q1_sales, df_q2_sales], ignore_index=False)

In [ ]:
df_combined_sales

# Pandas `apply()`

The `apply()` method is one of the most common methods for data preprocessing. It simplifies applying a function to each element in a Series and to each row (or column) in a DataFrame.

In [ ]:
# Apply a function to a Series. Let's revisit the example, such as calculating the average
# distance of the planets from the sun (in million kilometers).
# Let's say that we need to convert that distance to miles. How can we do that?

distances = {
    'Mercury': 57.9,
    'Venus': 108.2,
    'Earth': 149.6,
    'Mars': 227.9,
    'Jupiter': 778.5
}
s_distances_km = pd.Series(distances)
print(s_distances_km)

In [ ]:
# By using apply, we can define a function to do the conversion and then "apply" this function to the entire Series.

def kilometers_to_miles(kilometers):
    miles_per_kilometer = 0.621371
    return kilometers * miles_per_kilometer

s_distances_mi = s_distances_km.apply(kilometers_to_miles)
print(s_distances_mi)

The code above displays the contents of the `s_distances_mi` object and its data type.

The distances are converted to miles. To do so, we first define a function that performs the conversion, then pass the **function name without parentheses** to the `apply()` method. The `apply()` method takes each element in the Series and applies the `kilometers_to_miles()` function to it.

# Applying a Function on a Pandas DataFrame

Now, we are going to learn how to use the `apply()` method to manipulate columns and rows in a DataFrame.

But first, let's talk a bit about the **lambda function**.

In Python, a lambda function is a small, anonymous function defined using the `lambda` keyword. It can take any number of arguments but can only have one expression. Lambda functions are often used for short, simple operations that are easier to read and write in a single line. They are especially useful when you need a function for a short period, such as an argument to higher-order functions like `map()`, `filter()`, and `sorted()`. Lambda functions offer a concise way to perform operations without the need for formally defining a function using the `def` keyword. This makes them a handy tool for quick data manipulation and inline function definition.


Now, let's start by applying the `apply` function on a DataFrame.

First, we'll create a dummy DataFrame containing the personal details of a company's employees using the following snippet:

In [ ]:
df = pd.DataFrame({'EmployeeName': ['Callen Dunkley', 'Sarah Rayner', 'Jeanette Sloan', 'Kaycee Acosta', 'Henri Conroy', 'Emma Peralta', 'Martin Butt', 'Alex Jensen', 'Kim Howarth', 'Jane Burnett'],
                    'Department': ['Accounting', 'Engineering', 'Engineering', 'HR', 'HR', 'HR', 'Data Science', 'Data Science', 'Accounting', 'Data Science'],
                    'HireDate': [2010, 2018, 2012, 2014, 2014, 2018, 2020, 2018, 2020, 2012],
                    'Sex': ['M', 'F', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F'],
                    'Birthdate': ['04/09/1982', '14/04/1981', '06/05/1997', '08/01/1986', '10/10/1988', '12/11/1992', '10/04/1991', '16/07/1995', '08/10/1992', '11/10/1979'],
                    'Weight': [78, 80, 66, 67, 90, 57, 115, 87, 95, 57],
                    'Height': [176, 160, 169, 157, 185, 164, 195, 180, 174, 165],
                    'Kids': [2, 1, 0, 1, 1, 0, 2, 0, 3, 1]
                    })
df

Now, let's assume the HR team intends to send an invitation email that begins with a friendly greeting to all employees (e.g., "Hey, Sarah!").

They have requested the creation of two columns to store the employees' first and last names separately, making it easier to refer to the employees by their first names.

To accomplish this, we can utilize a lambda function that splits a string into a list after dividing it by the specified separator. The default separator character for the `split()` method is any whitespace.

In [ ]:
# Let's do it together!

Now, let's assume that the HR team wants to know every employee's age and the average age of the employees because they want to determine if an employee's age influences job satisfaction and work engagement.

To get the job done, the first step is to define a function that gets an employee's date of birth and returns their age:

In [ ]:
from datetime import datetime, date

# TODO: Complete the function
def calculate_age(birthdate):
    birthdate = datetime.strptime(birthdate, '%d/%m/%Y')
    age = 0  # How can we compute the age?
    # Remember, we need to verify if the person has already had a birthday this year.
    # To simplify, only consider the month.
    return age

df['Age'] = df['Birthdate'].apply(calculate_age)

# Exercise

The HR manager has requested that you provide the Body Mass Index (BMI) for every employee so they can obtain quotes from potential healthcare providers.

Note: The formula for the BMI is weight in kilograms divided by height in meters squared. Since the employees’ heights are measured in centimeters, it is necessary to divide the heights by 100 to convert them into meters.

$BMI = \frac{weight(kg)}{height(m)^2}$

In [ ]:
# TODO

# Complete the function
def calc_bmi(weight, height):
    pass

# The lambda function needs to take each row's weight and height values,
# then apply the calc_bmi() function on them to calculate their BMIs.
# Note that you need to pass the argument axis=1 to the apply() function to iterate over rows in the DataFrame.

# Pandas GroupBy

Pandas' `groupby` is a powerful feature in the Pandas library that allows for grouping data based on some criteria and then applying a function to each group independently. By using `groupby`, you can split your data into separate groups to perform computations for better analysis. For example, you might group a dataset by a category like gender or country, and then calculate the average age or total sales for each group. This method is instrumental in data exploration and preprocessing, making it easier to understand patterns and insights within different segments of your dataset.

# The 3 Steps of a GroupBy Process

Any `groupby` process involves some combination of the following three steps:

- Splitting the original object into groups based on the defined criteria.
- Applying a function to each group independently.
- Combining the results back together.

Let's explore this split-apply-combine chain step-by-step with an example from the Prize Dataset: file `prize_dataset.csv`.

In [ ]:
# First, let's load the dataset

df = pd.read_csv('prize_dataset.csv')

# TODO: Filter the dataset by the following columns: 
# 'awardYear', 'category', 'prizeAmount', 'prizeAmountAdjusted', 'name', 'gender', 'birth_continent'

#### Splitting the Original Object into Groups

Now, let's use the `DataFrame.groupby()` function to split the data into groups. We can do this along rows (by default, `axis=0`) or columns (`axis=1`).

For example, in our case, we can group the Nobel Prize data by prize category:

In [ ]:
grouped = df.groupby('category')
# If we try to print one of the GroupBy objects that we created, we will actually see no groups:
print(grouped)

It is important to note that creating a GroupBy object only checks if we have passed a correct mapping; it doesn't actually perform any operations of the split-apply-combine chain until we explicitly use some method on this object or extract some of its attributes.

In [ ]:
# To briefly inspect the resulting GroupBy object and check how the groups were exactly split, 
# we can extract the 'groups' or 'indices' attribute from it.

print(grouped.groups)
print(grouped.indices)

# Both attributes return a dictionary where the keys are the created groups, and the values are 
# lists of axis labels (for the 'groups' attribute) or indices (for the 'indices' attribute) 
# corresponding to the instances of each group in the original DataFrame:

In [ ]:
# To find the number of groups in a GroupBy object, we can use the 'ngroups' attribute 
# or call the 'len' function from the Python standard library.
print(grouped.ngroups)
print(len(grouped))

In [ ]:
# If we need to visualize all or some entries of each group, we can iterate over the GroupBy object:

# Each entry is a DataFrame!
for name, entry in grouped:
    print(f"Group: {name}")
    display(entry.head(2))  # Displays the first 2 entries of each group

In [ ]:
# If instead we want to select a single group in the form of a DataFrame,
# we can use the method get_group().

grouped.get_group('Literature')

# Applying a Function by Group

After splitting the original dataset, we can perform one of the following operations:

- **Aggregation**: Calculating a summary statistic for each group (e.g., group sizes, means, medians, or sums) and outputting a single number for many data points.
- **Transformation**: Conducting some operations by group, such as calculating the z-score for each group.
- **Filtration**: Rejecting some groups based on a predefined condition, such as group size, mean, median, or sum. This can also include filtering out particular rows from each group.

**Note: We will only focus on aggregation in this class.**

## Aggregation

To aggregate the data of a GroupBy object (i.e., to calculate a summary statistic by group), we can use the `agg()` method.

In [ ]:
grouped[['prizeAmount']].agg(["mean"])

# What are the other operations we could pass to agg?

## GroupBy Methods

Instead of using the `agg()` method, we can apply the corresponding pandas methods directly on a GroupBy object. 

The most common methods include:

- **Central Tendency Measures:**
  - `mean()`: Calculates the average value in each group.
  - `median()`: Finds the middle value in each group.
  - `mode()`: Identifies the most frequently occurring value(s) in each group.

- **Aggregation Functions:**
  - `sum()`: Adds up all numerical values in each group.

- **Counting Functions:**
  - `size()`: Counts the total number of entries in each group, including null values.
  - `count()`: Counts non-null entries in each group.

- **Range Functions:**
  - `min()`: Determines the smallest value in each group.
  - `max()`: Determines the largest value in each group.

- **Variability Measures:**
  - `std()`: Computes the standard deviation of each group, measuring the dispersion of the group's values.
  - `var()`: Computes the variance of each group, quantifying the spread of the group's values.

- **Uniqueness Function:**
  - `nunique()`: Provides the number of unique values in each group.

- **Descriptive Statistics:**
  - **`describe()`**: Outputs a summary of descriptive statistics including count, mean, std, min, 25%, 50%, 75%, and max values by group.

In [ ]:
grouped[['prizeAmount']].mean()