In [31]:
# Hello! I am a test cell. You can run me to see if your Python environment is working.
# Try pressing 'Ctrl + Enter' and see if you can see the message below.

print("If it is working, it is working. If it is not, it is not.")

If it is working, it is working. If it is not, it is not.

# Getting Started with Pandas

Pandas provides data structures and functions designed to make working with structured or tabular data intuitive and flexible. Moreover, it contains data structures and data manipulation tools intended to make data processing and analysis fast and convenient in Python.

It merges data manipulation capabilities found in spreadsheets and relational databases (such as SQL) with the power of Python. And it's really cool to work with.

**Pandas will be a major tool throughout this course! So, this is a very important notebook. You should become friends with this notebook and dream about it tonight.**

## The Dataset: Immigration to Canada from 1980 to 2013

Dataset source: https://www.un.org/development/desa/pd/data/international-migration-flows

In the same folder as this notebook, you will find a file called Canada.xlsx (check if you have it in the same folder locally on your machine).

The dataset contains annual data on international immigrants to Canada. We will explore it throughout this class :p

In [32]:
# To get started with Pandas, we need to import the library.
# Pythonic people (cool people who work with Python) conventionally work with Pandas using the alias `pd`:

import pandas as pd

Did you encounter any problems running the code above? Is your code producing any errors? Don't worry. If you have seen this message:

```python
ModuleNotFoundError: No module named 'pandas'
```

You need to install the Pandas package. To do that, open a terminal, activate the Conda environment, and install the package with the following commands:

```bash
# First, activate the Conda environment
conda activate dm_web

# Then, install the package
pip install pandas
pip install pyarrow  # <--- a required dependency of Pandas in the next major release. By installing it now, you can avoid annoying warning messages.
```

After installing the package, you may need to restart the notebook (click the "Restart" button above). After that, try to execute the cell above again.

**Note: This error will appear with any new package you want to use and haven't installed. In such cases, you will need to install the packages using pip.**

In [33]:
# Now, we are ready to go! Let's load the dataset into a Pandas dataframe:

df = pd.read_excel("Canada.xlsx")

Oh! Here we go again. Did your code encounter problems once more? So sad.

This time, you will read the error code and try to fix it by yourself. You know, I am old, and I will not be here forever.

In [34]:
# If you can see the table below it means you had success! But what are all these NaN in the data?!
# Open the Canada.xlsx file and check it structure

df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United Nations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Population Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Department of Economic and Social Affairs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,International Migration Flows to and from Sele...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,POP/DB/MIG/Flow/Rev.2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,December 2015 - Copyright © 2015 by United Nat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Suggested citation: United Nations, Department...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,International Migration Flows to and from Sel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Reporting country: Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Criterion: Citizenship,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Classification,NaN,Regional aggregates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012.0,2013.0
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN
24,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348.0,NaN
25,Immigrants,Foreigners,Africa,Western Africa,306,301,210,222,271,319,...,4333,5303,5751,5684,5511,6802,8355,6578,7834.0,NaN
26,Immigrants,Foreigners,Africa Total,NaN,3951,4363,3819,2671,2639,2650,...,28192,27523,29188,28284,29890,34534,40892,35441,38083.0,NaN
27,Immigrants,Foreigners,Asia,Central Asia,..,..,..,..,..,..,...,995,1134,903,936,805,962,905,769,1029.0,NaN
28,Immigrants,Foreigners,Asia,Eastern Asia,6836,8895,5481,3254,2624,2979,...,43550,50306,41763,35591,39602,37497,37954,35159,40449.0,NaN
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693,9191,9022,8845,12161,9787,...,18056,22809,25105,27256,30614,34166,44199,40494,37695.0,NaN
30,Immigrants,Foreigners,Asia,Southern Asia,11315,11566,11591,10157,9607,7654,...,58521,69510,66742,56032,54154,53083,62284,53673,60568.0,NaN
31,Immigrants,Foreigners,Asia,Western Asia,4181,4662,4120,2440,2882,3430,...,13728,15494,14541,13644,14719,15726,18503,16799,12477.0,NaN
32,Immigrants,Foreigners,Asia Total,NaN,31025,34314,30214,24696,27274,23850,...,134850,159253,149054,133459,139894,141434,163845,146894,152218.0,NaN
33,Immigrants,Foreigners,Europe,Eastern Europe,1467,3698,6873,5459,4433,3969,...,18360,16724,14389,13886,11988,11759,11803,9612,9464.0,NaN
34,Immigrants,Foreigners,Europe,Northern Europe,23721,26608,22134,10725,10845,10212,...,8486,8153,7969,9186,10042,9846,9816,7285,7616.0,NaN
35,Immigrants,Foreigners,Europe,Southern Europe,7762,7037,5222,3083,3033,2868,...,3200,2806,2417,2290,2692,2948,2661,2466,2854.0,NaN
36,Immigrants,Foreigners,Europe,Western Europe,6810,7459,8491,5371,3976,3795,...,8036,8272,8278,8133,9970,10525,9145,7415,9243.0,NaN
37,Immigrants,Foreigners,Europe Total,NaN,39760,44802,42720,24638,22287,20844,...,38082,35955,33053,33495,34692,35078,33425,26778,29177.0,NaN
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045,8310,8326,6998,5553,6048,...,6630,6816,6652,7826,8862,8847,10549,11958,11898.0,NaN
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734,921,1612,3648,4087,4862,...,3346,3990,4140,5039,4891,4814,5692,5821,6019.0,NaN
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302,5984,6831,4781,4038,4261,...,12205,13941,13884,13146,12794,13206,12577,10077,9256.0,NaN
41,Immigrants,Foreigners,Latin America and the Caribbean Total,NaN,13081,15215,16769,15427,13678,15171,...,22181,24747,24676,26011,26547,26867,28818,27856,27173.0,NaN
42,Immigrants,Foreigners,Northern America,Northern America,9378,10030,9074,7100,6661,6543,...,6990,8394,9613,9463,10190,8995,8142,7676,7891.0,NaN
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304,1119,848,457,481,467,...,1280,1279,1193,1383,1498,1538,1423,1226,1399.0,NaN
44,Immigrants,Foreigners,Oceania,Melanesia,632,707,816,558,391,448,...,497,300,278,304,331,313,401,316,273.0,NaN
45,Immigrants,Foreigners,Oceania,Micronesia,1,..,..,1,..,..,...,1,2,1,3,1,2,..,..,2.0,NaN
46,Immigrants,Foreigners,Oceania,Polynesia,5,13,11,2,6,5,...,10,4,1,3,4,7,10,6,5.0,NaN
47,Immigrants,Foreigners,Oceania Total,NaN,1942,1839,1675,1018,878,920,...,1788,1585,1473,1693,1834,1860,1834,1548,1679.0,NaN
48,Immigrants,Foreigners,Unknown,Unknown,44000,18078,16904,13635,14855,14368,...,3739,4785,4583,4348,4197,3402,3731,2554,1681.0,NaN

It turns out that we actually have distinct sheets in our dataset: "Regions by Citizenship" and "Canada by Citizenship."

Let's focus on the "Canada by Citizenship" sheet. Take a look at it. What do you see in the first lines?

Yes, we still have a problem; the Excel file has a header (the blue part) that is not formatted in a tabular way. So, we need to get rid of it when loading the data. Otherwise, we will load the DataFrame in the wrong way.

Since you are looking at the data, try to look at the lines of the data. What do you see in the last two lines?

Yes, it has some data that are not following the dataset format as well. Let's get rid of these two lines as well.

*"DataFrame? What is this?" We will talk about that soon.*

In [35]:
# Let's try to load the dataset again. But first, let's see what options the function provides to us.
# For this, let's use a feature provided by the notebook environment.
# We can see the parameters of a function in a Jupyter Notebook using the '?' symbol after the function name:

pd.read_excel?

# Check the signature below and try to find the parameter that will allow us to define the sheet name, skip some rows and skip the footer.

Signature:
pd.read_excel(
    io,
    sheet_name: 'str | int | list[IntStrT] | None' = 0,
    *,
    header: 'int | Sequence[int] | None' = 0,
    names: 'SequenceNotStr[Hashable] | range | None' = None,
    index_col: 'int | str | Sequence[int] | None' = None,
    usecols: 'int | str | Sequence[int] | Sequence[str] | Callable[[HashableT], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb', 'calamine'] | None" = None,
    converters: 'dict[str, Callable] | dict[int, Callable] | None' = None,
    true_values: 'Iterable[Hashable] | None' = None,
    false_values: 'Iterable[Hashable] | None' = None,
    skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None,
    nrows: 'int | None' = None,
    na_values=None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool' = False,
    parse_dates: 'list | dict | bool' = False,
    date_format: 'dict[Hashable, str] | str | None' = None,
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    comment: 'str | None' = None,
    skipfooter: 'int' = 0,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
    engine_kwargs: 'dict | None' = None,
) -> 'DataFrame | dict[IntStrT, DataFrame]'
Docstring:
Read an Excel file into a ``DataFrame``.

Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
read from a local filesystem or URL. Supports an option to read
a single sheet or a list of sheets.

Parameters
----------
io : str, ExcelFile, xlrd.Book, path object, or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, and file. For file URLs, a host is
    expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method,
    such as a file handle (e.g. via builtin ``open`` function)
    or ``StringIO``.

sheet_name : str, int, list, or None, default 0
    Strings are used for sheet names. Integers are used in zero-indexed
    sheet positions (chart sheets do not count as a sheet position).
    Lists of strings/integers are used to request multiple sheets.
    When ``None``, will return a dictionary containing DataFrames for each sheet.

    Available cases:

    * Defaults to ``0``: 1st sheet as a `DataFrame`
    * ``1``: 2nd sheet as a `DataFrame`
    * ``"Sheet1"``: Load sheet with name "Sheet1"
    * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
      as a dict of `DataFrame`
    * ``None``: Returns a dictionary containing DataFrames for each sheet.

header : int, list of int, default 0
    Row (0-indexed) to use for the column labels of the parsed
    DataFrame. If a list of integers is passed those row positions will
    be combined into a ``MultiIndex``. Use None if there is no header.
names : array-like, default None
    List of column names to use. If file contains no header row,
    then you should explicitly pass header=None.
index_col : int, str, list of int, default None
    Column (0-indexed) to use as the row labels of the DataFrame.
    Pass None if there is no such column.  If a list is passed,
    those columns will be combined into a ``MultiIndex``.  If a
    subset of data is selected with ``usecols``, index_col
    is based on the subset.

    Missing values will be forward filled to allow roundtripping with
    ``to_excel`` for ``merged_cells=True``. To avoid forward filling the
    missing values use ``set_index`` after reading the data instead of
    ``index_col``.
usecols : str, list-like, or callable, default None
    * If None, then parse all columns.
    * If str, then indicates comma separated list of Excel column letters
      and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
      both sides.
    * If list of int, then indicates list of column numbers to be parsed
      (0-indexed).
    * If list of string, then indicates list of column names to be parsed.
    * If callable, then evaluate each column name against it and parse the
      column if the callable returns ``True``.

    Returns a subset of the columns according to behavior above.
dtype : Type name or dict of column -> type, default None
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
    Use ``object`` to preserve data as stored in Excel and not interpret dtype,
    which will necessarily result in ``object`` dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
    If you use ``None``, it will infer the dtype of each column based on the data.
engine : {'openpyxl', 'calamine', 'odf', 'pyxlsb', 'xlrd'}, default None
    If io is not a buffer or path, this must be set to identify io.
    Engine compatibility :

    - ``openpyxl`` supports newer Excel file formats.
    - ``calamine`` supports Excel (.xls, .xlsx, .xlsm, .xlsb)
      and OpenDocument (.ods) file formats.
    - ``odf`` supports OpenDocument file formats (.odf, .ods, .odt).
    - ``pyxlsb`` supports Binary Excel files.
    - ``xlrd`` supports old-style Excel files (.xls).

    When ``engine=None``, the following logic will be used to determine the engine:

    - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
      then `odf <https://pypi.org/project/odfpy/>`_ will be used.
    - Otherwise if ``path_or_buffer`` is an xls format, ``xlrd`` will be used.
    - Otherwise if ``path_or_buffer`` is in xlsb format, ``pyxlsb`` will be used.
    - Otherwise ``openpyxl`` will be used.

converters : dict, default None
    Dict of functions for converting values in certain columns. Keys can
    either be integers or column labels, values are functions that take one
    input argument, the Excel cell content, and return the transformed
    content.
true_values : list, default None
    Values to consider as True.
false_values : list, default None
    Values to consider as False.
skiprows : list-like, int, or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int) at the
    start of the file. If callable, the callable function will be evaluated
    against the row indices, returning True if the row should be skipped and
    False otherwise. An example of a valid callable argument would be ``lambda
    x: x in [0, 2]``.
nrows : int, default None
    Number of rows to parse. Does not include header rows.
na_values : scalar, str, list-like, or dict, default None
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values. By default the following values are interpreted
    as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
    'n/a', 'nan', 'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is True, and ``na_values`` are specified,
      ``na_values`` is appended to the default NaN values used for parsing.
    * If ``keep_default_na`` is True, and ``na_values`` are not specified, only
      the default NaN values are used for parsing.
    * If ``keep_default_na`` is False, and ``na_values`` are specified, only
      the NaN values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is False, and ``na_values`` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
parse_dates : bool, list-like, or dict, default False
    The behavior is as follows:

    * ``bool``. If True -> try parsing the index.
    * ``list`` of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * ``dict``, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index contains an unparsable date, the entire column or
    index will be returned unaltered as an object data type. If you don`t want to
    parse some cells as date just change their type in Excel to "Text".
    For non-standard datetime parsing, use ``pd.to_datetime`` after
    ``pd.read_excel``.

    Note: A fast-path exists for iso8601-formatted dates.
date_format : str or dict of column -> format, default ``None``
    If used in conjunction with ``parse_dates``, will parse dates according to this
    format. For anything more complex,
    please read in as ``object`` and then apply :func:`to_datetime` as-needed.

    .. versionadded:: 2.0.0

thousands : str, default None
    Thousands separator for parsing string columns to numeric.  Note that
    this parameter is only necessary for columns stored as TEXT in Excel,
    any numeric columns will automatically be parsed, regardless of display
    format.
decimal : str, default '.'
    Character to recognize as decimal point for parsing string columns to numeric.
    Note that this parameter is only necessary for columns stored as TEXT in Excel,
    any numeric columns will automatically be parsed, regardless of display
    format.(e.g. use ',' for European data).
comment : str, default None
    Comments out remainder of line. Pass a character or characters to this
    argument to indicate comments in the input file. Any data between the
    comment string and the end of the current line is ignored.
skipfooter : int, default 0
    Rows at the end to skip (0-indexed).
storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

dtype_backend : {'numpy_nullable', 'pyarrow'}
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). If not specified, the default behavior
    is to not use nullable data types. If specified, the behavior
    is as follows:

    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
    * ``"pyarrow"``: returns pyarrow-backed nullable

    :class:`ArrowDtype` :class:`DataFrame`

    .. versionadded:: 2.0

engine_kwargs : dict, optional
    Arbitrary keyword arguments passed to excel engine.

Returns
-------
DataFrame or dict of DataFrames
    DataFrame from the passed in Excel file. See notes in sheet_name
    argument for more information on when a dict of DataFrames is returned.

See Also
--------
DataFrame.to_excel : Write DataFrame to an Excel file.
DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_fwf : Read a table of fixed-width formatted lines into DataFrame.

Notes
-----
For specific information on the methods used for each Excel engine, refer to the
pandas
:ref:`user guide <io.excel_reader>`

Examples
--------
The file can be read using the file name as string or an open file object:

>>> pd.read_excel("tmp.xlsx", index_col=0)  # doctest: +SKIP
       Name  Value
0   string1      1
1   string2      2
2  #Comment      3

>>> pd.read_excel(open("tmp.xlsx", "rb"), sheet_name="Sheet3")  # doctest: +SKIP
   Unnamed: 0      Name  Value
0           0   string1      1
1           1   string2      2
2           2  #Comment      3

Index and header can be specified via the `index_col` and `header` arguments

>>> pd.read_excel("tmp.xlsx", index_col=None, header=None)  # doctest: +SKIP
     0         1      2
0  NaN      Name  Value
1  0.0   string1      1
2  1.0   string2      2
3  2.0  #Comment      3

Column types are inferred but can be explicitly specified

>>> pd.read_excel(
...     "tmp.xlsx", index_col=0, dtype={"Name": str, "Value": float}
... )  # doctest: +SKIP
       Name  Value
0   string1    1.0
1   string2    2.0
2  #Comment    3.0

True, False, and NA values, and thousands separators have defaults,
but can be explicitly specified, too. Supply the values you would like
as strings or lists of strings!

>>> pd.read_excel(
...     "tmp.xlsx", index_col=0, na_values=["string1", "string2"]
... )  # doctest: +SKIP
       Name  Value
0       NaN      1
1       NaN      2
2  #Comment      3

Comment lines in the excel input file can be skipped using the
``comment`` kwarg.

>>> pd.read_excel("tmp.xlsx", index_col=0, comment="#")  # doctest: +SKIP
      Name  Value
0  string1    1.0
1  string2    2.0
2     None    NaN
File:      /opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/pandas/io/excel/_base.py
Type:      function

In [36]:
# Great! You found it. Right? Riiight?
# Now let's load the dataset, given the sheet_name and the list of rows it should skip. And do not forget to skip the footers!

# TODO: Load the dataset
df  = pd.read_excel("Canada.xlsx", header=20, sheet_name = "Canada by Citizenship")  # <--- complete the call
df

# Remove the comment from the line below to print the DataFrame
df.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [37]:
# To see the last lines in the dataset you can take a look at the tail
df.tail()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407
195,Immigrants,Foreigners,Unknown,999,World,999,World,999,World,44000,...,3739,4785,4583,4348,4197,3402,3731,2554,1681,1484
196,Immigrants,Both,Total,999,World,999,World,999,World,143137,...,235822,262242,251640,236753,247244,252170,280687,248748,257903,259021

## Pandas Dataframes

In the line above, you created a Pandas DataFrame. A DataFrame is a two-dimensional and highly flexible data structure provided by Pandas. It is one of the most commonly used data structures for data manipulation and analysis in data science and data engineering.

Throughout this course, the DataFrame will be one of our main "data units." What does that mean? We will always handle the data by loading it into a DataFrame, and from there, we will use other libraries to generate all sorts of visualizations. Be friends with your DataFrames; they are very powerful and can be used not only in data visualization but also in data analysis. Let's explore a little bit of that in the sequence.

In [38]:
# When working with a dataset, it's always good to start by checking the basic information about your dataframe.
# We can do that by using the info() method:

df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Type      197 non-null    str
 1   Coverage  197 non-null    str
 2   OdName    197 non-null    str
 3   AREA      197 non-null    int64
 4   AreaName  197 non-null    str
 5   REG       197 non-null    int64
 6   RegName   197 non-null    str
 7   DEV       197 non-null    int64
 8   DevName   197 non-null    str
 9   1980      197 non-null    int64
 10  1981      197 non-null    int64
 11  1982      197 non-null    int64
 12  1983      197 non-null    int64
 13  1984      197 non-null    int64
 14  1985      197 non-null    int64
 15  1986      197 non-null    int64
 16  1987      197 non-null    int64
 17  1988      197 non-null    int64
 18  1989      197 non-null    int64
 19  1990      197 non-null    int64
 20  1991      197 non-null    int64
 21  1992      197 non-null    int64
 22  1993      197 non-null    int64
 23  1994      197 non-null    int64
 24  1995      197 non-null    int64
 25  1996      197 non-null    int64
 26  1997      197 non-null    int64
 27  1998      197 non-null    int64
 28  1999      197 non-null    int64
 29  2000      197 non-null    int64
 30  2001      197 non-null    int64
 31  2002      197 non-null    int64
 32  2003      197 non-null    int64
 33  2004      197 non-null    int64
 34  2005      197 non-null    int64
 35  2006      197 non-null    int64
 36  2007      197 non-null    int64
 37  2008      197 non-null    int64
 38  2009      197 non-null    int64
 39  2010      197 non-null    int64
 40  2011      197 non-null    int64
 41  2012      197 non-null    int64
 42  2013      197 non-null    int64
dtypes: int64(37), str(6)
memory usage: 66.3 KB

The main types stored in Pandas are float, int, bool, datetime64[ns], datetime64[ns, tz], timedelta[ns], category, and object (string). 
In addition, these types have item sizes, e.g., int64 and int32.

**What are the types we have in this dataset?**

In [39]:
# We can also see the size of the dataframe (rows, columns)
df.shape

(197, 43)

In [40]:
# Let's clean the dataset to remove a few unnecessary columns. We can use the pandas drop() method for that.

# First, let's create a list with the columns we want to drop.
columns = ['AREA', 'REG', 'DEV', 'Type', 'Coverage']
# Then, let's drop them.
# In pandas, axis=0 represents rows (default), and axis=1 represents columns.
df.drop(columns, axis=1, inplace=True)

# After cleaning it up, let's see the first 10 lines.
df.head(10)

,OdName,AreaName,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1
5,Angola,Africa,Middle Africa,Developing regions,1,3,6,6,4,3,...,268,295,184,106,76,62,61,39,70,45
6,Antigua and Barbuda,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,42,52,...,14,24,32,15,32,38,27,37,51,25
7,Argentina,Latin America and the Caribbean,South America,Developing regions,368,426,626,241,237,196,...,1591,1153,847,620,540,467,459,278,263,282
8,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,147,224,218,198,205,267,252,236,258,207
9,Australia,Oceania,Australia and New Zealand,Developed regions,702,639,484,317,317,319,...,930,909,875,1033,1018,1018,933,851,982,1121

In [41]:
# The column names are not nice. Let's rename the columns so they can be as nice as we are.

# First, let's create a dictionary mapping the old names to the new coolest ones.
new_names = {'OdName': 'Country', 'AreaName': 'Continent', 'RegName': 'Region'}

# Now, let's rename the columns.
df.rename(columns=new_names, inplace=True)

In [42]:
# TODO: Check the names of the columns. Are they the new names?
df

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,...,124,161,140,122,133,128,211,160,174,217
193,Zambia,Africa,Eastern Africa,Developing regions,11,17,11,7,16,9,...,56,91,77,71,64,60,102,69,46,59
194,Zimbabwe,Africa,Eastern Africa,Developing regions,72,114,102,44,32,29,...,1450,615,454,663,611,508,494,434,437,407
195,Unknown,World,World,World,44000,18078,16904,13635,14855,14368,...,3739,4785,4583,4348,4197,3402,3731,2554,1681,1484
196,Total,World,World,World,143137,128641,121175,89185,88272,84346,...,235822,262242,251640,236753,247244,252170,280687,248748,257903,259021

As you can see, the number of immigrants is distributed over a range of years (from 1980 to 2013). It would be interesting to have a column with the total, wouldn't it?

Let's do it. Let's create a column called "Total" that sums up the total immigrants by country over the entire period.

But first, we need to create a list with all the years we want to sum up. We could do it like this: year_columns = ['1980', '1981', '1982', '1983', '1984', '1985', ...]

But there are 33 years!!! So let's be smart and create a function for that.

In [43]:
# TODO: Finish the function below to create a list with all the years we have in the dataset.
# Note: the years are integers
def create_list():
    years = []
    for column in range(4, len(df.columns)-1):
        years.append(df.columns[column])
    return years    


year_columns = create_list()

# Check if the list has all the years we need.
print(year_columns)

[1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012]

In [44]:
# Now that we have the list we finally can create the Total Column
df['Total'] = df[year_columns].sum(axis=1)

# Remember: 
# axis=0 would sum the values vertically, resulting in a single sum for each column.
# axis=1 sums the values horizontally, resulting in a sum for each row, which is what we want when creating a "Total" column for each row in a dataset.

In [45]:
# Check the Total column
df.head(20)

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,56635
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15096
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,65108
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,14
5,Angola,Africa,Middle Africa,Developing regions,1,3,6,6,4,3,...,295,184,106,76,62,61,39,70,45,2068
6,Antigua and Barbuda,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,42,52,...,24,32,15,32,38,27,37,51,25,956
7,Argentina,Latin America and the Caribbean,South America,Developing regions,368,426,626,241,237,196,...,1153,847,620,540,467,459,278,263,282,19314
8,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,224,218,198,205,267,252,236,258,207,3103
9,Australia,Oceania,Australia and New Zealand,Developed regions,702,639,484,317,317,319,...,909,875,1033,1018,1018,933,851,982,1121,22708
10,Austria,Europe,Western Europe,Developed regions,234,238,201,117,127,165,...,122,102,98,91,109,124,84,102,90,4895
11,Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,359,236,203,125,165,209,138,161,57,2592
12,Bahamas,Latin America and the Caribbean,Caribbean,Developing regions,26,23,38,12,21,28,...,14,18,23,30,27,25,40,60,55,753
13,Bahrain,Asia,Western Asia,Developing regions,0,2,1,1,1,3,...,12,12,22,9,35,28,21,39,32,443
14,Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,...,4171,4014,2897,2939,2104,4721,2694,2640,3789,61779
15,Barbados,Latin America and the Caribbean,Caribbean,Developing regions,372,376,299,244,265,285,...,111,97,130,134,125,121,97,132,97,6826
16,Belarus,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,558,439,568,524,454,438,357,277,247,7728
17,Belgium,Europe,Western Europe,Developed regions,511,540,519,297,183,181,...,400,302,363,335,358,363,332,402,379,10383
18,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,...,37,24,28,48,38,39,36,34,53,1030
19,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,...,95,116,183,205,238,290,284,391,397,2455

# Pandas Slicing


## Select Column

Did you see what we did in the previous cell? We indexed our DataFrame using the columns. This is called Slicing. 
We can generate subdatasets by selecting the columns we want.

There are two ways to filter by column name:

- Method 1: Very easy and intuitive, but only works for column names that do NOT have spaces or special characters. It will return a series (We will talk about that soon).
```python
    df.column_name               # returns a series
```
- Method 2: The one we used previously. It can filter on multiple columns.
```python
    df['column']                  # returns a series like df.column_name
    df[['column 1', 'column 2']]  # returns a DataFrame
```

In [46]:
# Let's try filtering on the list of countries ('Country').
df.Country

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
192             Yemen
193            Zambia
194          Zimbabwe
195           Unknown
196             Total
Name: Country, Length: 197, dtype: str

In [47]:
# Now, let's filter the list of countries ('Country') and the data for the years: 1980 - 1985.

# TODO: Add the years.
df[['Country'] + list(range(1980, 1986))]

            Country    1980    1981    1982   1983   1984   1985
0       Afghanistan      16      39      39     47     71    340
1           Albania       1       0       0      0      0      0
2           Algeria      80      67      71     69     63     44
3    American Samoa       0       1       0      0      0      0
4           Andorra       0       0       0      0      0      0
..              ...     ...     ...     ...    ...    ...    ...
192           Yemen       1       2       1      6      0     18
193          Zambia      11      17      11      7     16      9
194        Zimbabwe      72     114     102     44     32     29
195         Unknown   44000   18078   16904  13635  14855  14368
196           Total  143137  128641  121175  89185  88272  84346

[197 rows x 7 columns]

# Selecting Rows

**WARNING: THIS IS A VERY IMPORTANT TOPIC!**

We can also select rows. There are different ways to do that:

1. Using `.loc[]` to select rows based on labels or conditions.
    ```python
    df.loc[row_label]  # Select a single row by its label
    df.loc[start_label:end_label]  # Select a range of rows by their labels
    df.loc[df['Column'] == 'Value']  # Select rows based on a condition
    ```
2. Using `.iloc[]` to select rows based on integer positions.
    ```python
    df.iloc[row_index]  # Select a single row by its integer position
    df.iloc[start_index:end_index]  # Select a range of rows by their integer positions
    ```

3. Using Conditions: You can filter rows based on conditions using boolean indexing.
    ```python
    df[df['Column'] == 'Value']  # Select rows where a specific condition is met
    ```
4. Using `.query()`: The `.query()` method allows you to filter rows using a query expression.
    ```python
    df.query('Column == "Value"')  # Select rows based on a query expression
    ```

In [48]:
# Let's do it together!
# 1. How can we select the line of Japan?
df.query('Country == "Japan"')
# 2. How can we select the countries from Asia?
df.query('Continent == "Asia"')
# 3. How can we select the countries from Asia that have fewer than 5K immigrants to Canada?
df.query('Continent == "Asia" and Total < 5000')
# 4. How can we select the row of 2011 for the countries from Asia that have fewer than 5k immigrants?
df.query('Continent == "Asia" and Total < 5000')[["Country", 2011]]

                                        Country  2011
8                                       Armenia   236
11                                   Azerbaijan   138
13                                      Bahrain    21
25                            Brunei Darussalam     6
38   China, Macao Special Administrative Region    13
46                                       Cyprus     6
48        Democratic People's Republic of Korea    97
66                                      Georgia   139
92                                       Kuwait    58
93                                   Kyrgyzstan   159
94             Lao People's Democratic Republic    22
106                                    Maldives     3
114                                    Mongolia   103
129                                        Oman    10
139                                       Qatar     3
151                                Saudi Arabia   278
170                                  Tajikistan    47
178                                Turkmenistan    20
182                        United Arab Emirates    60
187                                  Uzbekistan   162
192                                       Yemen   160

In [49]:
# TODO: Using .loc[], Check the number of immigrants from France for the following scenarios:

# 1. The full row data (all columns)
df.loc[df['Country'] == 'France']
# 2. For year 2000
df.loc[df['Country'] == 'France', 2000]

# 3. For years 1990 to 1995
df.loc[df['Country'] == 'France', 1990:1995]

    1990  1991  1992  1993  1994  1995
63  2177  2911  3487  3709  2759  3332

In [73]:
# TODO: Check the data from Europe for two different regions: Western and Southern.
europe_regions = df.query('Region in ["Western Europe", "Southern Europe"]')
# Display the dataframe and find out how many instances (rows) are there for each one of the regions.
europe_regions["Region"].value_counts()

Region
Southern Europe    14
Western Europe      9
Name: count, dtype: int64

### Sorting Values of a DataFrame

The `sort_values()` function is used to sort a DataFrame or a Series based on one or more columns.

You have to specify one or more columns by which you want to sort and the order (ascending or descending).

```python
df.sort_values(col_name, axis=0, ascending=True, inplace=False, ignore_index=False)
```

- `col_name` - the column(s) to sort by.
- `axis` - axis along which to sort. 0 for sorting by rows (default) and 1 for sorting by columns.
- `ascending` - to sort in ascending order (True, default) or descending order (False).
- `inplace` - to perform the sorting operation in-place (True) or return a sorted copy (False, default).
- `ignore_index` - to reset the index after sorting (True) or keep the original index values (False, default).

In [51]:
# Let's sort out the dataframe in descending order to find out the top 10 countries that has the most imigrations to Canada

df_sorted = df.sort_values("Total", ascending=False, axis=0, inplace=False)
df_sorted = df_sorted[df_sorted["Country"] != "Total"]

In [52]:
# TODO: Print the top 10 countries
df_sorted.head(10)

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
79,India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,658817
36,China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,...,42584,33518,27642,30037,29622,30391,28502,33024,34129,625833
183,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,Developed regions,22045,24796,20620,10015,10170,9564,...,7258,7140,8216,8979,8876,8724,6204,6195,5827,545673
195,Unknown,World,World,World,44000,18078,16904,13635,14855,14368,...,4785,4583,4348,4197,3402,3731,2554,1681,1484,513575
136,Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,...,18139,18400,19837,24887,28573,38617,36765,34315,29544,481847
185,United States of America,Northern America,Northern America,Developed regions,9378,10030,9074,7100,6661,6543,...,8394,9613,9463,10190,8995,8142,7676,7891,8501,232621
130,Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,228997
81,Iran (Islamic Republic of),Asia,Southern Asia,Developing regions,1172,1429,1822,1592,1977,1648,...,5837,7480,6974,6475,6580,7477,7479,7534,11291,164632
162,Sri Lanka,Asia,Southern Asia,Developing regions,185,371,290,197,1086,845,...,4930,4714,4123,4756,4547,4422,3309,3338,2394,145964
137,Poland,Europe,Eastern Europe,Developed regions,863,2930,5881,4546,3588,2819,...,1405,1263,1235,1267,1013,795,720,779,852,138389

In [61]:
# TODO: Find out top 3 countries that contributes the most to immigration to Canda in the year 1992.
# Display the country names with the immigrant count in this year
df_sorted_1992 = df.sort_values(1992, ascending=False, axis=0, inplace=False)
df_sorted_1992 = df_sorted_1992[df_sorted_1992["Country"] != "Total"]
df_sorted_1992.head(3)[["Country", 1992]]

                                               Country   1992
183  United Kingdom of Great Britain and Northern I...  34123
195                                            Unknown  33100
79                                               India  13673